In [3]:
import numpy as np
myarr=np.array([1,2,3,4,5])
print(myarr)

[1 2 3 4 5]


In [4]:
import numpy as np

arr = np.array([1,56,90,4,6])

print(arr)

[ 1 56 90  4  6]


In [5]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
import numpy as np

arr = np.array([["Maths, English, Urdu"], ["Python, Java, PHP"]])

print(arr)

[['Maths, English, Urdu']
 ['Python, Java, PHP']]


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3]) 

7


In [17]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])

2nd element on 1st dim:  2


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:4])

[2 3 4]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [28]:
from numpy import random

x = random.rand()

print(x)

0.5934013939813587


In [29]:
arr2 = np.random.rand(3,4) #(rows,columns) #2 dimensional array
arr2

array([[0.27935602, 0.43040296, 0.06995818, 0.04818233],
       [0.19635796, 0.83058698, 0.9402502 , 0.82602628],
       [0.39509779, 0.6832808 , 0.36231334, 0.68064495]])